display: Define init script modules properly.
error: 'hardware/qcom/display/init/init.qti.display_boot.sh': The file was not recognized as a valid object file

Change-Id: Icaa0d0d718c4dbe06fd417b2b4cfad56e4dd0513
(cherry picked from commit 8759a300f62c54bec3758290d85d2275e3579e3f)