libdebug: Fix namespace import
error: hardware/qcom/display/libdebug/Android.bp:4:1: "libdisplaydebug" depends on undefined module "qtidisplay_common_defaults".
Module "libdisplaydebug" is defined in namespace "hardware/qcom/display/libdebug" which can read these 2 namespaces: ["hardware/qcom/display/libdebug" "."]