display: Export libdisplaydebug to soong dependencies
error: hardware/qcom/display/oem_services/Android.bp:4:1: "libfilefinder" depends on undefined module "libdisplaydebug".
Module "libfilefinder" is defined in namespace "hardware/qcom/display" which can read these 4 namespaces: ["hardware/qcom/display" "vendor/qcom/opensource/commonsys-intf/display" "vendor/qcom/opensource/display"
"."]
Module "libdisplaydebug" can be found in these namespaces: ["hardware/qcom/display/libdebug" "hardware/qcom/sdm845/display" "hardware/qcom/sm7250/display" "hardware/qcom/sm8150/display"]
Or did you mean ["display_headers" "libdisplaydoc"]?
error: hardware/qcom/display/libdrmutils/Android.bp:1:1: "libdrmutils" depends on undefined module "libdisplaydebug".
Module "libdrmutils" is defined in namespace "hardware/qcom/display" which can read these 4 namespaces: ["hardware/qcom/display" "vendor/qcom/opensource/commonsys-intf/display" "vendor/qcom/opensource/display" ".
"]
Module "libdisplaydebug" can be found in these namespaces: ["hardware/qcom/display/libdebug" "hardware/qcom/sdm845/display" "hardware/qcom/sm7250/display" "hardware/qcom/sm8150/display"]
Or did you mean ["display_headers" "libdisplaydoc"]?

Co-authored-by: Alessandro Astone <ales.astone@gmail.com>