Fix -Wformat errors with explicit void* -> char* cast.
hardware/qcom/sm7250/display/sde-drm/drm_plane.cpp:439:12: error: format specifies type 'char *' but the argument has type 'void *' [-Werror,-Wformat]
           blob->data, blob->length);
           ^~~~~~~~~~

hardware/qcom/sm7250/display/sde-drm/drm_connector.cpp:497:12: error: format specifies type 'char *' but the argument has type 'void *' [-Werror,-Wformat]
           blob->data, blob->length);
           ^~~~~~~~~~

hardware/qcom/sm7250/display/sde-drm/drm_connector.cpp:580:12: error: format specifies type 'char *' but the argument has type 'void *' [-Werror,-Wformat]
           blob->data, blob->length);
           ^~~~~~~~~~

hardware/qcom/sm7250/display/sde-drm/drm_crtc.cpp:308:12: error: format specifies type 'char *' but the argument has type 'void *' [-Werror,-Wformat]
           blob->data, blob->length);
           ^~~~~~~~~~

Bug: http://b/155835175
Bug: http://b/169166735
Test: m
Change-Id: I73ae1f5f4bccedd2e19f865bd1122a09de00aa76
(cherry picked from commit 06916233e7ed0b98d2950c92497f84dcbe589b75)